### ISSUE TITLE
Embed into NEW Google Sites

### ISSUE THREAD

**Issue by yellowjaguar5** [augnustin/google-docs-publisher#18]
Hello!
I just came across gdoc.pub and it is exactly what I was looking for! I'm trying to use it to embed a google doc into a [(new) Google Site](sites.google.com/new). Right now, I've tried using the URL first given, gdoc.pub/<hash> and gdoc.pub/<hash>/raw. Both do nothing. Is there a different way to go about embedding into the new Google Sites?
Thanks!

**Comment by aug-riedinger** [comment]
Hi @yellowjaguar5 :smile: 

Did not know about the Google Site service. Neat! 
I shall help you into integrating the gdoc.pub into your site, but I have the impression this feature is already integrated by default into google docs, isn't it?

![image](https://user-images.githubusercontent.com/1970156/29428172-8d9c3048-838c-11e7-8cfc-ce1e39499f24.png)

**Comment by yellowjaguar5** [comment]
Yes, this feature is supported. However, the document does not appear in its entirety, it shows a section and a scroll bar. [Here is a site that demonstrates this (and a few other options).](https://sites.google.com/crystal.csus.org/embedded-doc-example/home) I was wondering if it was possible to use this project to make **the entire document show without a scroll bar**. It would also be convenient if gdoc.pub supported the new google sites in general.
Thanks!

**Comment by yellowjaguar5** [comment]
I just re-read my response and I see exactly what you mean. 🙃 
I figured out another solution recently.
Thanks for your help!
