### ISSUE TITLE
Using with Google Sheets?

### ISSUE THREAD

**Issue by brianjking** [augnustin/google-docs-publisher#2]
Hello,

Is it possible to use this with Google Sheets? If so, which publish format should I choose?

Thanks!

**Comment by aug-riedinger** [comment]
Hi Brianjking,
This is not possible for now but it could definitely be done if you tell me you'd need this. I hadn't tried the 'Publish to the web..." feature on a google spreadsheet til now, but it seems to work fairly the same way than Docs.
Regarding the size, I guess it depends on the original file also. If you'd like, you could send me some examples that you'd be happy to have included in http://gdoc.pub and we'll improve the current app with this feature along with the documents need.
Would that be ok for you?

**Comment by Wirsing84** [comment]
I second this - Google Spreadsheets would be great for use as a nice dashboard... However, the style is more than just ugly when coming directly from Google

**Comment by augnustin** [comment]
Interesting! I shall have a second look at it then :smile:

**Comment by augnustin** [comment]
Despite I could give it a go, there will always be cases where display breaks, and it will require many edge-cases handling. 

How about @Wirsing84 embedding the table in another web page?

![image](https://user-images.githubusercontent.com/1970156/31430431-17e1ed9c-ae71-11e7-927b-52cf2e48d51c.png)

This should fit your need and the whole responsiveness issues will be left to the wrapping page. 

But let me know if that wouldn't suit your need!

**Comment by augnustin** [comment]
Hello guys,

I just added the possibility to use gdoc.pub with spreadsheets.

Here's an example : https://gdoc.pub/sheet/e/2PACX-1vTj1Tj8aDCRE4SSH_QZXZNvJ5DT33owuopS65s4PqS1qdB7cOnRxB_CE_1LR84EXWfDvUHgakA2Bzpn

Please try it and let me know how this works for your!

**Comment by Wirsing84** [comment]
Hey there,
that is pretty awesome, thanks a bunch! Works great for normal worksheets.
Sadly, the Dashboard we created consists of diagram charts, non of which are displayed in the docs-pubklisher output.
<img width="835" alt="screen shot 2017-11-20 at 22 28 05" src="https://user-images.githubusercontent.com/1714308/33042441-2da19132-ce42-11e7-93b7-ce0d00d7d614.png">

Any idea why charts dont work?

Cheers,
Chris

**Comment by augnustin** [comment]
Hi Chris,

I can have a look but I need the URL of the document to investigate. If you are unconfortable making it public, please write me there: https://augustin-riedinger.fr/contact/

Best

**Comment by augnustin** [comment]
I'm closing now. If you still have trouble, please reach me.

Best
