### ISSUE TITLE
error message instead of doc

### ISSUE THREAD

**Issue by dimbill** [augnustin/google-docs-publisher#20]
Hello and congrats for your nice work.
I tested your publish solution with some personal files and it worked like a charm, but then I tried to use it in a project I am helping with and it either gives "Internal Server Error " or just says "Found" but doesn't display the anything more. 
The link I I was working with was 

https://docs.google.com/document/d/e/2PACX-1vQ254uFJrS3krkyjtcSC22nY2ZA44KHS4E4hFnpi4bFWs8wtJwMtnZrDDYPVFTmznbcWOtwPm08kJhK/pub

but there are several docs showing one of the messages I wrote above.
I don't know whether the links inside the docs could cause the result most of the ones I used contain links.

**Comment by augnustin** [comment]
Hello @dimbill 

Thanks for your feedback.
I fixed the issue regarding your document:
https://gdoc.pub/doc/e/2PACX-1vQ254uFJrS3krkyjtcSC22nY2ZA44KHS4E4hFnpi4bFWs8wtJwMtnZrDDYPVFTmznbcWOtwPm08kJhK

Have fun using gdoc.pub !
