### ISSUE TITLE
Frozen rows in published googlesheets

### ISSUE THREAD

**Issue by Bullinachinashop** [augnustin/google-docs-publisher#22]
Hi google sheets introduction - works brilliantly, however, is there a workaround so that if frozen rows are used in the original google sheet this can be carried across as well?

**Comment by augnustin** [comment]
Hello @Bullinachinashop 

I am afraid there are few chances I can do something about it. If it is not in the published by google version of the document, then I won't have a chance.

Anyway, if you want me to have a further look, I'll need you to send me an example of the document.

If you are uncomfortable of making the document public, you can send it to me via: https://augustin-riedinger.fr/contact/ 

Best

**Comment by augnustin** [comment]
I'm closing for now. Please reopen if you are still facing the issue.

Best
