### ISSUE TITLE
Document too big

### ISSUE THREAD

**Issue by plbowers** [augnustin/google-docs-publisher#24]
I have several chapters of a book I am publishing on the web and 2 of them result in this error message:

WARNING: Document too big
Your document is too big to be displayed with gdoc.pub. Try reducing it's size or use the original document URL.

Thanks for your comprehension,

Augustin Riedinger

Is there any possibility the maximum size could be increased slightly? Or perhaps is there some way I could host your source on my own server and increase the size allowed?

**Comment by augnustin** [comment]
Hi @plbowers 

I will have a look. Please send me the url of the document at https://augustin-riedinger.fr/contact

Best

**Comment by plbowers** [comment]
I divided the 2 long sections into part A and part B so that they both fit now.

Thanks for being willing. Apologies for taking your time.

**Comment by augnustin** [comment]
Glad you've sorted yourself out. 

Best
