### ISSUE TITLE
cannot go to bookmarks

### ISSUE THREAD

**Issue by plbowers** [augnustin/google-docs-publisher#25]
I tried 

<gdoc.pub link>#bookmark=id.8mgz4l4x3h0t
and
<gdoc.pub link>#id.8mgz4l4x3h0t

but neither of them goes to my anchor. I confirmed that the anchor exists and is spelled correctly. I put the anchor in by means of the insert/bookmark capabilities in google docs.

I confirmed that this

<google doc published to web link>#id.8mgz4l4x3h0t

does take me to my anchor. It just looks crappy because it doesn't have your software displaying it... :-)

**Comment by augnustin** [comment]
I'm not sure I understand what you mean by  `<gdoc.pub link>#bookmark=id.8mgz4l4x3h0t`.

I have had anchor links working successfully in the past so there should be a solution.

Don't use the gdoc.pub url. Instead only refer to the hash anchor. If you can read basic HTML, this would look like: `<a href="#id.8mgz4l4x3h0t">My content</a>`. 

If you still have issues, you can send me the document there: https://augustin-riedinger.fr/contact

Good luck

**Comment by plbowers** [comment]
From another source (from the table of contents) I want to be able to link directly to a section within one of the documents. 

You are right that within the document I can make internal anchors (in that same web-page) work. But I am wanting to come from outside and go directly to a place within that document. That's why I'm starting with the <gdoc.pub link> and appending the anchor after that...

Does that make sense?

**Comment by augnustin** [comment]
It surely makes sense. 

You could use gdoc.pub URLs in your document. Then the link URL would be `https://gdoc.pub/doc/<document_id>#<anchor_name>`. Eg. https://gdoc.pub/doc/1lhIQmky05-KV3Elfnk1tTM7syjawodSoXa5AEhXT0fY#id.8mgz4l4x3h0t

While testing it, I found a bug that I just fixed, so let me know if it works better now.

**Comment by plbowers** [comment]
Hah! Now it works! Either the bug you fixed took care of it or else it was my user error previously. In any event, it all seems fine now - THANK YOU!
